### ISSUE TITLE
Faraday::Error::ConnectionFailed: Network is unreachable - connect(2) 

### ISSUE THREAD

**Issue by rajofchennai** [arsduo/koala#345]
I keep getting these errors when i call the facebook api. This does not happen everytime but it is very random. This is the trace. I use ruby 2.0.0-p247 with rails 3.2.13

```
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1367:in `request'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/net.rb:33:in `request_with_newrelic_trace'
/home/ubuntu/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1126:in `get'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/adapter/net_http.rb:73:in `perform_request'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/adapter/net_http.rb:38:in `call'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/request/url_encoded.rb:14:in `call'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/request/multipart.rb:13:in `call'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/connection.rb:253:in `run_request'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/connection.rb:106:in `get'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/koala-1.6.0/lib/koala/http_service.rb:78:in `make_request'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/koala-1.6.0/lib/koala.rb:51:in `make_request'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/koala-1.6.0/lib/koala/api.rb:51:in `api'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/koala-1.6.0/lib/koala/api/graph_api.rb:468:in `graph_call'
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247@spaghetti/ruby/2.0.0/gems/koala-1.6.0/lib/koala/api/graph_api.rb:58:in `get_object'
```

**Comment by Pysis868** [comment]
For me, this happened on my system when trying to perform a gem download, completely unrelated to koala, and it was because for our project, we need to download its gems through a proxy, and have the "HTTP_PROXY" terminal environment variable set, along with "HTTPS_PROXY".  These seem to enable a proxy path for common commands such as curl, and maybe even wget as well.

So that may be your problem.
