### ISSUE TITLE
Cannot update facebook post using koala put_connection method

### ISSUE THREAD

**Issue by lisa-lina** [arsduo/koala#482]
Hi there,

From the facebook graph api, I can update a post using like this:
/{page-id}_{message-id}  add a field called {message}, set a new value {value}
trigger a post request, facebook returns success status.

![1](https://cloud.githubusercontent.com/assets/1336072/9080472/98ea8efe-3b86-11e5-8bec-beeda0300e24.jpg)

But using ruby irb, i got below error:
{code}
1.9.3-p286 :027 > @graph.put_connections("1496450497258312_1666770910226269", "feed", :message=>"update post 123")
Koala::Facebook::ClientError: type: OAuthException, code: 100, message: (#100) 1496450497258312_1666770910226269 does not resolve to a valid user ID [HTTP 400]
        from /home/vagrant/.rvm/gems/ruby-1.9.3-p286/gems/koala-2.0.0/lib/koala/api/graph_api.rb:500:in `block in graph_call'
        from /home/vagrant/.rvm/gems/ruby-1.9.3-p286/gems/koala-2.0.0/lib/koala/api.rb:76:in `api'
        from /home/vagrant/.rvm/gems/ruby-1.9.3-p286/gems/koala-2.0.0/lib/koala/api/graph_api.rb:498:in `graph_call'
        from /home/vagrant/.rvm/gems/ruby-1.9.3-p286/gems/koala-2.0.0/lib/koala/api/graph_api.rb:147:in `put_connections'
        from (irb):27
        from /home/vagrant/.rvm/rubies/ruby-1.9.3-p286/bin/irb:16:in `<main>'

{code}

since using facebook's post request, we can update post, I assume we should support that using the koala's post api

**Comment by cedricmatalog** [comment]
where you able to find the solution?
