### ISSUE TITLE
"Please reduce the amount of data you're asking for" when using koala.delete_connections

### ISSUE THREAD

**Issue by alfredoreduarte** [arsduo/koala#564]
Hi! I'm making a simple request to delete a page tab, something that worked until like yesterday:

```
koala = Koala::Facebook::API.new(page_token)
params = {
	tab: 'app_' + self.fb_application.app_id
}
koala.delete_connections('me', 'tabs', params)
```

And now I'm getting this weird error. How am I supposed to limit this if I'm only deleting one item? I couldn't find a similar case among the older issues.

```
Koala::Facebook::ServerError: code: 1, message: Please reduce the amount of data you're asking for, then retry your request [HTTP 500]
  from koala/api.rb:77:in `api'
  from koala/api/graph_api.rb:527:in `graph_call'
  from koala/api/graph_api.rb:165:in `delete_connections'
  from app/models/application.rb:115:in `delete_tab_on_facebook'
  from app/controllers/applications_controller.rb:105:in `uninstall_tab'
  from action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  from abstract_controller/base.rb:188:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:20:in `block in process_action'
  from active_support/callbacks.rb:126:in `call'
  from active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:101:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from action_controller/metal/rescue.rb:20:in `process_action'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:21:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from action_controller/metal/instrumentation.rb:30:in `process_action'
  from action_controller/metal/params_wrapper.rb:248:in `process_action'
  from active_record/railties/controller_runtime.rb:18:in `process_action'
  from abstract_controller/base.rb:126:in `process'
  from action_view/rendering.rb:30:in `process'
  from action_controller/metal.rb:190:in `dispatch'
  from action_controller/metal.rb:262:in `dispatch'
  from action_dispatch/routing/route_set.rb:50:in `dispatch'
  from action_dispatch/routing/route_set.rb:32:in `serve'
  from action_dispatch/journey/router.rb:39:in `block in serve'
  from action_dispatch/journey/router.rb:26:in `each'
  from action_dispatch/journey/router.rb:26:in `serve'
  from action_dispatch/routing/route_set.rb:725:in `call'
  from rack/deflater.rb:35:in `call'
  from warden/manager.rb:35:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from rack/etag.rb:25:in `call'
  from rack/conditional_get.rb:38:in `call'
  from rack/head.rb:12:in `call'
  from rack/session/abstract/id.rb:222:in `context'
  from rack/session/abstract/id.rb:216:in `call'
  from action_dispatch/middleware/cookies.rb:613:in `call'
  from action_dispatch/middleware/callbacks.rb:38:in `block in call'
  from active_support/callbacks.rb:97:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_call_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:36:in `call'
  from action_dispatch/middleware/remote_ip.rb:79:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  from action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from rails/rack/logger.rb:36:in `call_app'
  from rails/rack/logger.rb:24:in `block in call'
  from active_support/tagged_logging.rb:69:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:69:in `tagged'
  from rails/rack/logger.rb:24:in `call'
  from action_dispatch/middleware/request_id.rb:24:in `call'
  from rack/method_override.rb:22:in `call'
  from rack/runtime.rb:22:in `call'
  from action_dispatch/middleware/executor.rb:12:in `call'
  from action_dispatch/middleware/static.rb:136:in `call'
  from rack/sendfile.rb:111:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from rack/cors.rb:80:in `call'
  from rails/engine.rb:522:in `call'
  from puma/configuration.rb:225:in `call'
  from puma/server.rb:578:in `handle_request'
  from puma/server.rb:415:in `process_client'
  from puma/server.rb:275:in `block in run'
  from puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by arsduo** [comment]
Hi! That's a really bizarre issue. Unfortunately it's coming directly from Facebook (probably some API change they've made), so I don't know what specifically needs to be changed to make it work. I suggest posting this question on [facebook.stackoverflow.com](http://facebook.stackoverflow.com) — I believe Facebook still uses that as their official developer forum.

If it turns out to be something we should change with Koala, definitely reopen this issue and we'll get it fixed!
